package main

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// This fixture is a REAL key4.db + logins.json generated by the NSS library
// (PK11SDR_Encrypt), not by our own encoder. It is the regression guard for
// decrypting genuine Thunderbird/Firefox credential stores — in particular the
// PBKDF2 prf AlgorithmIdentifier that NSS writes with no parameters, which an
// earlier revision of the ASN.1 structs rejected as a (nonexistent) master
// password. The stored login is imap://imap.example.com / alice@example.com
// with password "s3cret-imap"; there is no master password.
var _ = Describe("LoadCredentials against a real NSS key4.db", func() {
	It("decrypts a genuinely NSS-encrypted login", func() {
		creds, err := LoadCredentials("testdata/realnss")
		Expect(err).NotTo(HaveOccurred())
		pw, ok := creds.Lookup("imap.example.com", "alice@example.com")
		Expect(ok).To(BeTrue())
		Expect(pw).To(Equal("s3cret-imap"))
	})
})
